name: Deploy to QA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        run: |
          VERSION=$(cat VERSION)
          echo "Deployed version $VERSION to QA"

      - name: Simulate Deployment
        run: echo "Dummy deployment to QA environment complete."
