name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        run: |
          VERSION=$(cat VERSION)
          echo "Deployed version $VERSION to Development"

      - name: Simulate Deployment
        run: echo "Dummy deployment to Development environment complete."
